from __future__ import annotations

METHOD_LIBRARY: dict[str, list[dict[str, object]]] = {
    "triangle_area": [
        {
            "name": "Heron",
            "conditions": ["three_sides_known"],
            "requirements": ["three_sides_known"],
            "steps": ["compute_semiperimeter", "apply_heron_formula"],
            "equations": [
                "s = (a + b + c)/2",
                "Area = sqrt(s*(s-a)*(s-b)*(s-c))",
            ],
            "keywords": ["heron", "semiperimeter", "all sides", "three sides"],
            "base_score": 9.5,
        },
        {
            "name": "Base-Height",
            "conditions": ["base_and_height_known"],
            "requirements": ["base_known", "height_known"],
            "steps": ["identify_base", "identify_height", "apply_area_formula"],
            "equations": ["Area = (1/2) * base * height"],
            "keywords": ["base", "height", "altitude"],
            "base_score": 8.5,
        },
        {
            "name": "Trigonometric Area",
            "conditions": ["two_sides_known", "included_angle_known"],
            "requirements": ["two_sides_known", "included_angle_known"],
            "steps": ["identify_two_sides", "apply_trig_area_formula"],
            "equations": ["Area = (1/2)ab sin(C)"],
            "keywords": ["sin", "sine", "included angle", "two sides and angle"],
            "base_score": 7.2,
        },
    ],
    "circle_area": [
        {
            "name": "Radius Formula",
            "conditions": ["radius_known"],
            "requirements": ["radius_known"],
            "steps": ["apply_circle_area_formula"],
            "equations": ["Area = pi*r^2"],
            "keywords": ["radius", "pi", "r squared"],
            "base_score": 9.5,
        },
        {
            "name": "Diameter Conversion",
            "conditions": ["diameter_known"],
            "requirements": ["diameter_known"],
            "steps": ["convert_diameter_to_radius", "apply_circle_area_formula"],
            "equations": ["r = d/2", "Area = pi*r^2"],
            "keywords": ["diameter", "radius", "half of diameter"],
            "base_score": 8.7,
        },
        {
            "name": "Circumference Backsolve",
            "conditions": ["circumference_known"],
            "requirements": ["circumference_known"],
            "steps": ["solve_for_radius_from_circumference", "apply_circle_area_formula"],
            "equations": ["C = 2*pi*r", "r = C/(2*pi)", "Area = pi*r^2"],
            "keywords": ["circumference", "2 pi r"],
            "base_score": 7.8,
        },
    ],
    "rectangle_measurement": [
        {
            "name": "Area Formula",
            "conditions": ["length_and_width_known", "goal_is_area"],
            "requirements": ["length_known", "width_known"],
            "steps": ["multiply_length_and_width"],
            "equations": ["Area = length * width"],
            "keywords": ["length", "width", "rectangle area"],
            "base_score": 9.4,
        },
        {
            "name": "Perimeter Formula",
            "conditions": ["length_and_width_known", "goal_is_perimeter"],
            "requirements": ["length_known", "width_known"],
            "steps": ["double_length_width_sum"],
            "equations": ["Perimeter = 2(length + width)"],
            "keywords": ["perimeter", "2 l plus w"],
            "base_score": 9.4,
        },
    ],
    "linear_equation": [
        {
            "name": "Isolation",
            "conditions": ["single_variable_equation"],
            "requirements": ["single_variable_equation"],
            "steps": ["collect_like_terms", "inverse_operations", "isolate_variable"],
            "equations": ["ax + b = c", "x = (c-b)/a"],
            "keywords": ["isolate", "balance", "move term", "divide both sides"],
            "base_score": 9.3,
        },
        {
            "name": "Balance Method",
            "conditions": ["single_variable_equation"],
            "requirements": ["single_variable_equation"],
            "steps": ["apply_same_operation_both_sides", "simplify"],
            "equations": ["left = right", "left + k = right + k"],
            "keywords": ["both sides", "balance", "same operation"],
            "base_score": 8.8,
        },
    ],
    "quadratic_equation": [
        {
            "name": "Factoring",
            "conditions": ["quadratic_equation_present", "factorable_quadratic"],
            "requirements": ["quadratic_equation_present"],
            "steps": ["rewrite_quadratic", "factor_expression", "zero_product_rule"],
            "equations": ["ax^2 + bx + c = 0", "(mx+n)(px+q)=0"],
            "keywords": ["factor", "roots", "zero product"],
            "base_score": 9.2,
        },
        {
            "name": "Quadratic Formula",
            "conditions": ["quadratic_equation_present"],
            "requirements": ["quadratic_equation_present"],
            "steps": ["identify_coefficients", "apply_quadratic_formula"],
            "equations": ["x = (-b +- sqrt(b^2 - 4ac)) / (2a)"],
            "keywords": ["quadratic formula", "discriminant"],
            "base_score": 8.9,
        },
        {
            "name": "Completing the Square",
            "conditions": ["quadratic_equation_present"],
            "requirements": ["quadratic_equation_present"],
            "steps": ["normalize_quadratic", "complete_square", "solve_square_equation"],
            "equations": ["x^2 + bx = -c", "(x + b/2)^2 = d"],
            "keywords": ["complete the square", "perfect square"],
            "base_score": 8.1,
        },
    ],
    "system_of_linear_equations": [
        {
            "name": "Substitution",
            "conditions": ["system_two_equations"],
            "requirements": ["system_two_equations"],
            "steps": ["solve_one_equation_for_variable", "substitute_into_other", "back_substitute"],
            "equations": ["y = mx + b", "ax + b(mx + c) = d"],
            "keywords": ["substitute", "plug into", "back substitute"],
            "base_score": 8.8,
        },
        {
            "name": "Elimination",
            "conditions": ["system_two_equations"],
            "requirements": ["system_two_equations"],
            "steps": ["align_equations", "eliminate_variable", "back_substitute"],
            "equations": ["a1x + b1y = c1", "a2x + b2y = c2"],
            "keywords": ["eliminate", "add equations", "subtract equations"],
            "base_score": 9.0,
        },
    ],
    "percentage": [
        {
            "name": "Percent Equation",
            "conditions": ["percent_problem"],
            "requirements": ["percent_problem"],
            "steps": ["convert_statement_to_percent_equation", "solve_percent_equation"],
            "equations": ["part = percent * whole", "percent = part/whole"],
            "keywords": ["percent", "out of 100", "whole", "part"],
            "base_score": 9.2,
        },
        {
            "name": "Decimal Conversion",
            "conditions": ["percent_problem"],
            "requirements": ["percent_problem"],
            "steps": ["convert_percent_to_decimal", "multiply_by_base"],
            "equations": ["p% = p/100", "value = decimal * base"],
            "keywords": ["decimal", "divide by 100", "multiply by base"],
            "base_score": 8.8,
        },
    ],
    "ratio_proportion": [
        {
            "name": "Scaling",
            "conditions": ["ratio_problem"],
            "requirements": ["ratio_problem"],
            "steps": ["sum_ratio_parts", "find_scale_factor", "scale_each_part"],
            "equations": ["total = k(r1 + r2 + ...)", "part = k * ratio_part"],
            "keywords": ["ratio", "parts", "scale factor", "share"],
            "base_score": 9.1,
        },
        {
            "name": "Unit Rate",
            "conditions": ["ratio_problem"],
            "requirements": ["ratio_problem"],
            "steps": ["reduce_to_one_unit", "scale_to_needed_total"],
            "equations": ["unit = quantity / ratio_total"],
            "keywords": ["unit rate", "one part"],
            "base_score": 8.4,
        },
    ],
    "speed_distance_time": [
        {
            "name": "Rate Formula",
            "conditions": ["speed_distance_time_problem"],
            "requirements": ["speed_distance_time_problem"],
            "steps": ["identify_known_values", "apply_rate_formula"],
            "equations": ["distance = speed * time", "speed = distance/time", "time = distance/speed"],
            "keywords": ["speed", "distance", "time", "rate"],
            "base_score": 9.3,
        },
        {
            "name": "Unit Conversion + Rate Formula",
            "conditions": ["speed_distance_time_problem", "unit_conversion_needed"],
            "requirements": ["speed_distance_time_problem"],
            "steps": ["convert_units", "apply_rate_formula"],
            "equations": ["distance = speed * time"],
            "keywords": ["convert", "minutes to hours", "km to m"],
            "base_score": 8.5,
        },
    ],
    "probability_basic": [
        {
            "name": "Favorable Over Total",
            "conditions": ["probability_problem"],
            "requirements": ["probability_problem"],
            "steps": ["count_favorable_outcomes", "count_total_outcomes", "form_probability_ratio"],
            "equations": ["P(E) = favorable/total"],
            "keywords": ["favorable", "total outcomes", "probability"],
            "base_score": 9.2,
        },
        {
            "name": "Complement Rule",
            "conditions": ["probability_problem", "complement_language"],
            "requirements": ["probability_problem"],
            "steps": ["find_complement_event", "subtract_from_one"],
            "equations": ["P(E) = 1 - P(not E)"],
            "keywords": ["complement", "not", "at least one"],
            "base_score": 8.7,
        },
    ],
    "mean_average": [
        {
            "name": "Sum Over Count",
            "conditions": ["average_problem"],
            "requirements": ["average_problem"],
            "steps": ["sum_data", "divide_by_count"],
            "equations": ["mean = sum(values)/count(values)"],
            "keywords": ["mean", "average", "sum", "count"],
            "base_score": 9.4,
        },
    ],
    "simple_interest": [
        {
            "name": "Simple Interest Formula",
            "conditions": ["simple_interest_problem"],
            "requirements": ["principal_known", "rate_known", "time_known"],
            "steps": ["identify_principal_rate_time", "apply_simple_interest_formula"],
            "equations": ["SI = (P * R * T)/100", "Amount = P + SI"],
            "keywords": ["simple interest", "principal", "rate", "time", "amount"],
            "base_score": 9.3,
        },
    ],
}
